name: 'K8s Manifest Updater'
description: 'Update Kubernetes manifests with new container images'
author: 'restack'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  app_id:
    description: 'GitHub App ID'
    required: true
  private_key:
    description: 'GitHub App Private Key'
    required: true
  installation_id:
    description: 'GitHub App Installation ID'
    required: false
  image:
    description: 'The new image to set (e.g. my-image:v2)'
    required: true
  yaml_path:
    description: 'Path to the field to update (e.g. spec.template.spec.containers[0].image). Supports array selection like apps[name=my-app].'
    required: false
  nested_yaml_path:
    description: 'If the target field is a stringified YAML, this is the path inside that string to update.'
    required: false
  container_name:
    description: 'Deprecated: Use yaml_path instead. The name of the container to update.'
    required: false
  manifest_repo:
    description: 'Repository containing manifests'
    required: true
  manifest_path:
    description: 'Path to manifest file'
    default: 'k8s/deployment.yaml'
  branch:
    description: 'Branch to update'
    default: 'main'
  create_pr:
    description: 'Create PR instead of direct push'
    default: 'false'

outputs:
  commit_sha:
    description: 'SHA of the commit created'
  pr_url:
    description: 'URL of PR if created'

runs:
  using: 'node20'
  main: 'dist/index.js'
